import { Worker } from "bullmq";
import { unlink } from "fs/promises";
import { existsSync } from "fs";
import path from "path";
import os from "os";

import redisConnection from "../configs/redis.js";
import LLMService from "../services/LLMService.js";
import EmbeddingService from "../services/EmbeddingService.js";
import StorageService from "../services/StorageService.js";
import checkSemanticCache from "../utils/checkSemanticCache.js";
import saveToCache from "../utils/saveToCache.js";
import buildPptxFile from "../utils/buildPptxFile.js";
import updateJobStatus from "../utils/updateJobStatus.js";
import saveAiMetrics from "../utils/saveAiMetrics.js";
import logger from "../services/LoggerService.js";

const llmService = new LLMService();
const embeddingService = new EmbeddingService();
const storageService = new StorageService();

const MAX_PPT_RETRIES = 3;
const MAX_S3_RETRIES = 3;

// Attempts to build the PPTX, retrying on failure
const buildPptxWithRetry = async (slideContent, tempFilePath) => {
	for (let attempt = 1; attempt <= MAX_PPT_RETRIES; attempt++) {
		try {
			await buildPptxFile(slideContent, tempFilePath);
			return;
		} catch (err) {
			if (attempt === MAX_PPT_RETRIES) throw err;
		}
	}
};

// Attempts to upload to S3, retrying on failure (reuses existing temp file)
const uploadWithRetry = async (tempFilePath, s3Key) => {
	for (let attempt = 1; attempt <= MAX_S3_RETRIES; attempt++) {
		try {
			await storageService.uploadFile(tempFilePath, s3Key);
			return;
		} catch (err) {
			if (attempt === MAX_S3_RETRIES) throw err;
		}
	}
};

// Main job processor
const processJob = async (job) => {
	const { jobId, topic, grade, numberOfSlides } = job.data;

	const tempFilePath = path.join(os.tmpdir(), `ppt_${jobId}`);
	const actualFilePath = `${tempFilePath}.pptx`;

	await updateJobStatus(jobId, { status: "processing" });
	logger.info("JOB_PROCESSING", "Job picked up by worker", { jobId });

	try {
		const cacheKey = `${topic} grade ${grade} ${numberOfSlides} slides`;
		const embedding = await embeddingService.getEmbedding(cacheKey);

		let slideContent = await checkSemanticCache(embedding);

		if (!slideContent) {
			// Cache miss — generate fresh content from LLM
			const start = process.hrtime.bigint();
			const { slideContent: generated, metrics } = await llmService.generateSlideContent(
				topic,
				grade,
				numberOfSlides,
			);
			const durationMs = Number(process.hrtime.bigint() - start) / 1_000_000;

			slideContent = generated;

			logger.success(
				"LLM_CONTENT_GENERATED",
				"Slide content generated by LLM",
				{ jobId, modelUsed: metrics.modelUsed },
				durationMs,
			);

			await saveAiMetrics(jobId, metrics);
			await saveToCache(embedding, slideContent);

			logger.info("CACHE_SAVED", "Slide content saved to semantic cache", { jobId });
		} else {
			// Cache hit — slide_content is stored as a JSON string in DB
			slideContent = typeof slideContent === "string" ? JSON.parse(slideContent) : slideContent;
			logger.info("CACHE_HIT", "Slide content served from semantic cache", { jobId });
		}

		const s3Key = `presentations/${jobId}.pptx`;

		// Build PPTX
		const pptStart = process.hrtime.bigint();
		await buildPptxWithRetry(slideContent, tempFilePath);
		const pptDurationMs = Number(process.hrtime.bigint() - pptStart) / 1_000_000;
		logger.success(
			"PPT_BUILT",
			"PPTX file created on disk",
			{ jobId, tempFilePath: actualFilePath },
			pptDurationMs,
		);

		// Upload to S3
		const uploadStart = process.hrtime.bigint();
		await uploadWithRetry(actualFilePath, s3Key);
		const uploadDurationMs = Number(process.hrtime.bigint() - uploadStart) / 1_000_000;
		logger.success("PPT_UPLOADED", "PPTX file uploaded to S3", { jobId, s3Key }, uploadDurationMs);

		await updateJobStatus(jobId, { status: "done", s3Key });
		logger.success("JOB_DONE", "Job completed successfully", { jobId });
	} catch (err) {
		logger.error("JOB_FAILED", "Job processing failed", { jobId, error: err.message, stack: err.stack });
		await updateJobStatus(jobId, {
			status: "failed",
			errorMessage: "Presentation generation failed. Please try again.",
		});
	} finally {
		// Always clean up temp file
		if (existsSync(actualFilePath)) {
			await unlink(actualFilePath).catch(() => {});
			logger.info("TEMP_FILE_REMOVED", "Temporary PPTX file deleted from disk", { jobId, path: actualFilePath });
		}
	}
};

// Worker with concurrency of 5 as specified
const pptWorker = new Worker("pptQueue", processJob, {
	connection: redisConnection,
	concurrency: 5,
});

pptWorker.on("failed", (job, err) => {
	logger.error("WORKER_JOB_FAILED", "BullMQ worker reported job failure", {
		jobId: job?.data?.jobId,
		error: err.message,
	});
});

export default pptWorker;
